### ISSUE TITLE
k8s dashboard无法显示cpu、mem等监控数据（kubectl top node也无数据）

### ISSUE THREAD

**Issue by raopeng** [bmwx4/k8s-in-practice#10]
环境：
系统------Centos Linux release 7.6.1810
内核------5.0.9-1.el7.elrepo.x86_64

1. heapster 、dashboard、influxdb均为running状态，cadvisor正常
[root@k8s-master01 ~]# kubectl get po -n kube-system 
NAME                                    READY   STATUS    RESTARTS   AGE
coredns-56684f94d6-xpprt                1/1     Running   0          5d8h
heapster-54866d8f99-mnlzh               1/1     Running   0          101m
kubernetes-dashboard-65f974f565-55g4c   1/1     Running   0          5d7h
monitoring-grafana-758d9c6f87-5wnb9     1/1     Running   0          169m
monitoring-influxdb-cdcfd8485-g4776     1/1     Running   0          169m

2. kubectl logs heapster 一直有如下报错：
E0525 12:13:01.961814       1 reflector.go:190] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:89: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kube-system:heapster" cannot list resource "namespaces" in API group "" at the cluster scope
E0525 12:13:01.964088       1 reflector.go:190] k8s.io/heapster/metrics/heapster.go:328: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:kube-system:heapster" cannot list resource "pods" in API group "" at the cluster scope

3. heapster 的yaml文件关键配置如下：
spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: fishchen/heapster-amd64:v1.5.3
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default?kubeletHttps=true&kubeletPort=10250&insecure=true
        - --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086

4. rbac 的yaml 配置文件如下：
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: heapster-kubelet-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kubelet-api-admin
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system

**Comment by MrYueQ** [comment]
rbac 的yaml 文件不全。
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: heapster-kubelet-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kubelet-api-admin
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system
