### ISSUE TITLE
kubectl port-forward   socat not found

### ISSUE THREAD

**Issue by yan20190120** [bmwx4/k8s-in-practice#15]
kubectl port-forward  时报错  uid : unable to do port forwarding: socat not found

需要在代理pod  所在的node  安装 socat

yum -y install socat

**Comment by guanyuding** [comment]
哦，是的，是依赖 socat 这个工具的，另外 socat 这个工具还是很强大的，可以多用用，你也可以补充到文档里。

**Comment by guanyuding** [comment]
I turned this issue off first. @yan20190120
